project_id = "lbwdluddlmyizemfiswp"

[functions.chat-hr]
verify_jwt = false

[functions.empregare-proxy]
verify_jwt = false

[functions.sync-empregare]
verify_jwt = false

[functions.generate-job-description]
verify_jwt = false

[functions.invite-user]
verify_jwt = false
